const sampleAgent = [
  {
    id: "1561ccfb-2708-403c-aec2-8df660e78923",
    agent_name: "Robert Williams",
    user_name: "robertw",
    address: "123 Sunset Blvd, Miami, FL",
    password: "hashedpassword123",
    email: "robert.williams@example.com",
    state: "Florida",
    city: "Miami",
    pincode: "33101",
    mobile: "3216549870",
    nominee: "Emma Williams",
    document: "passport.pdf",
    document_type: "passport",
    assign_insurance_plan: "Life Insurance",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "0cb385bf-143f-4b73-ac92-9bbb0816cba6",
    agent_name: "Sophia Martinez",
    user_name: "sophiam",
    address: "789 Ocean Dr, San Francisco, CA",
    password: "hashedpassword456",
    email: "sophia.martinez@example.com",
    state: "California",
    city: "San Francisco",
    pincode: "94103",
    mobile: "6547893210",
    nominee: "Carlos Martinez",
    document: "idcard.png",
    document_type: "ID Card",
    assign_insurance_plan: "Health Insurance",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "2020671d-2e49-4546-b532-f0ca9873ec14",
    agent_name: "Liam Anderson",
    user_name: "liama",
    address: "456 Pine St, Seattle, WA",
    password: "hashedpassword789",
    email: "liam.anderson@example.com",
    state: "Washington",
    city: "Seattle",
    pincode: "98101",
    mobile: "9871236540",
    nominee: "Olivia Anderson",
    document: "license.jpg",
    document_type: "Driver License",
    assign_insurance_plan: "Car Insurance",
    created_at: new Date(),
    updated_at: new Date(),
  },
];

module.exports = sampleAgent;
