const sampleCustomers = [
  {
    id: "0e836c93-3088-4311-86cf-44e98415cfd8",
    customer_name: "John Doe",
    user_name: "johndoe",
    address: "123 Main St, New York, NY",
    password: "hashedpassword123",
    email: "john.doe@example.com",
    state: "New York",
    city: "New York",
    pincode: "10001",
    mobile: "1234567890",
    nominee: "Jane Doe",
    document: "passport.jpg",
    document_type: "passport",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "5ac03ad9-c26a-4d05-a35f-ad2440a705c6",
    customer_name: "Alice Smith",
    user_name: "alicesmith",
    address: "456 Elm St, Los Angeles, CA",
    password: "hashedpassword456",
    email: "alice.smith@example.com",
    state: "California",
    city: "Los Angeles",
    pincode: "90001",
    mobile: "9876543210",
    nominee: "Bob Smith",
    document: "idcard.pdf",
    document_type: "ID Card",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "b3741af1-0664-435d-bbf7-d6d2522e70f6",
    customer_name: "Michael Johnson",
    user_name: "michaelj",
    address: "789 Oak St, Chicago, IL",
    password: "hashedpassword789",
    email: "michael.johnson@example.com",
    state: "Illinois",
    city: "Chicago",
    pincode: "60601",
    mobile: "1122334455",
    nominee: "Sarah Johnson",
    document: "license.png",
    document_type: "Driver License",
    created_at: new Date(),
    updated_at: new Date(),
  },
];

module.exports = sampleCustomers;
