const sampleEmployee = [
  {
    id: "745cb154-859a-484f-8674-92a8c5bf8a0d",
    employee_name: "David Johnson",
    user_name: "davidj",
    address: "789 Broadway St, New York, NY",
    password: "hashedpassword123",
    email: "david.johnson@example.com",
    state: "New York",
    city: "New York",
    pincode: "10001",
    mobile: "1234567890",
    nominee: "Emma Johnson",
    document: "passport.pdf",
    document_type: "Passport",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "a372dbc5-1286-49f0-8636-7d4177259520",
    employee_name: "Laura Smith",
    user_name: "lauras",
    address: "456 Maple St, Los Angeles, CA",
    password: "hashedpassword456",
    email: "laura.smith@example.com",
    state: "California",
    city: "Los Angeles",
    pincode: "90001",
    mobile: "9876543210",
    nominee: "Michael Smith",
    document: "idcard.png",
    document_type: "ID Card",
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: "b2830d4e-6b07-43e0-9946-51711c7c636f",
    employee_name: "Mark Anderson",
    user_name: "marka",
    address: "123 Pine St, Chicago, IL",
    password: "hashedpassword789",
    email: "mark.anderson@example.com",
    state: "Illinois",
    city: "Chicago",
    pincode: "60601",
    mobile: "1122334455",
    nominee: "Sarah Anderson",
    document: "license.jpg",
    document_type: "Driver License",
    created_at: new Date(),
    updated_at: new Date(),
  },
];

module.exports = sampleEmployee;
